repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
        exclude: docs/*
    - id: trailing-whitespace
        exclude: docs/*
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: no-commit-to-branch
        args: [-b main]
- repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    - id: pyupgrade
        files: "py$"
- repo: https://github.com/astral-sh/ruff-pre-commit
# Ruff version.
rev: v0.5.4
hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
