[package]
name = "haiko_agent"
version = "0.1.1"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
orion_numbers = { git = "https://github.com/gizatechxyz/orion.git", branch = "cleaning" }
orion_data_structures = { git = "https://github.com/gizatechxyz/orion.git", branch = "cleaning" }
orion_algo = { git = "https://github.com/gizatechxyz/orion.git", branch = "cleaning" }

[dev-dependencies]
cairo_test = "2.7.0"

[tool.agent]
definitions = "proto/oracle.proto"  # required
# cairo_output = "src"
# oracle_lock = "Oracle.lock"
# servers_config = "servers.json"

[cairo]
enable-gas = false
